[package]
name = "weekly"
version = "0.1.0"
authors = ["gmadrid"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
chrono = "0.4.19"
printpdf = "0.3.4"
